
import { EmployeeRange, PlanType, PricingTable, ProgramFeeTable, RequeUnit, ExamItem } from './types';

export const EMPLOYEE_RANGES: EmployeeRange[] = [
  { id: 'R1', min: 1, max: 5, label: '01 a 05 Vidas' },
  { id: 'R2', min: 6, max: 10, label: '06 a 10 Vidas' },
  { id: 'R3', min: 11, max: 15, label: '11 a 15 Vidas' },
  { id: 'R4', min: 16, max: 20, label: '16 a 20 Vidas' },
  { id: 'R5', min: 21, max: 25, label: '21 a 25 Vidas' },
  { id: 'R6', min: 26, max: 30, label: '26 a 30 Vidas' },
  { id: 'R7', min: 31, max: 35, label: '31 a 35 Vidas' },
  { id: 'R8', min: 36, max: 40, label: '36 a 40 Vidas' },
  { id: 'R9', min: 41, max: 45, label: '41 a 45 Vidas' },
  { id: 'R10', min: 46, max: 50, label: '46 a 50 Vidas' },
  { id: 'R11', min: 51, max: 55, label: '51 a 55 Vidas' },
  { id: 'R12', min: 56, max: 60, label: '56 a 60 Vidas' },
  { id: 'R13', min: 61, max: 65, label: '61 a 65 Vidas' },
  { id: 'R14', min: 66, max: 70, label: '66 a 70 Vidas' },
  { id: 'R15', min: 71, max: 75, label: '71 a 75 Vidas' },
  { id: 'R16', min: 76, max: 80, label: '76 a 80 Vidas' },
  { id: 'R17', min: 81, max: 85, label: '81 a 85 Vidas' },
  { id: 'R18', min: 86, max: 90, label: '86 a 90 Vidas' },
  { id: 'R19', min: 91, max: 95, label: '91 a 95 Vidas' },
  { id: 'R20', min: 96, max: 100, label: '96 a 100 Vidas' },
  { id: 'R21', min: 101, max: 110, label: '101 a 110 Vidas' },
  { id: 'R22', min: 111, max: 120, label: '111 a 120 Vidas' },
  { id: 'R23', min: 121, max: 130, label: '121 a 130 Vidas' },
  { id: 'R24', min: 131, max: 140, label: '131 a 140 Vidas' },
  { id: 'R25', min: 141, max: 150, label: '141 a 150 Vidas' },
  { id: 'R26', min: 151, max: 160, label: '151 a 160 Vidas' },
  { id: 'R27', min: 161, max: 170, label: '161 a 170 Vidas' },
  { id: 'R28', min: 171, max: 180, label: '171 a 180 Vidas' },
  { id: 'R29', min: 181, max: 190, label: '181 a 190 Vidas' },
  { id: 'R30', min: 191, max: 200, label: '191 a 200 Vidas' },
];

export const MONTHLY_VALUES_EXPRESS: PricingTable = {
  R1: 55, R2: 75, R3: 100, R4: 125, R5: 145, R6: 160, R7: 175, R8: 190, R9: 205, R10: 220,
  R11: 235, R12: 250, R13: 265, R14: 275, R15: 285, R16: 295, R17: 310, R18: 320, R19: 335, R20: 345,
  R21: 370, R22: 395, R23: 420, R24: 445, R25: 470, R26: 495, R27: 520, R28: 545, R29: 570, R30: 595,
};

export const MONTHLY_VALUES_PRO: PricingTable = {
  R5: 145, R6: 160, R7: 175, R8: 190, R9: 205, R10: 220, R11: 235, R12: 245, R13: 260, R14: 270,
  R15: 285, R16: 295, R17: 310, R18: 320, R19: 335, R20: 345, R21: 370, R22: 395, R23: 420, R24: 445,
  R25: 470, R26: 495, R27: 520, R28: 545, R29: 570, R30: 595,
};

export const PROGRAM_FEES_TABLE: ProgramFeeTable = {
  R1: 350, R2: 400, R3: 450, R4: 500, R5: 550, R6: 600, R7: 650, R8: 700, R9: 750, R10: 800,
  R11: 850, R12: 900, R13: 950, R14: 1000, R15: 1050, R16: 1100, R17: 1150, R18: 1200, R19: 1250, R20: 1300,
  R21: 1380, R22: 1460, R23: 1540, R24: 1620, R25: 1700, R26: 1780, R27: 1860, R28: 1940, R29: 2020, R30: 2100,
};

export const PLAN_SERVICES: Record<PlanType, string[]> = {
  [PlanType.EXPRESS]: [
    'Elaboração de PGR',
    'Elaboração de PCMSO',
    'eSocial/PPP eletrônico',
    'Exames Ocupacionais'
  ],
  [PlanType.ESSENCIAL]: [
    'Elaboração de PGR',
    'Elaboração de PCMSO',
    'eSocial/PPP eletrônico',
    'Exames Ocupacionais',
    'Sistema de Gestão de SST',
    'Ordem de Serviço',
    'Controle de entrega de EPI',
    'Gestão de Treinamentos',
    'Relatórios de Convocação de Periódicos',
    'Agendamento Online'
  ],
  [PlanType.PRO]: [
    'Elaboração de PGR',
    'Elaboração de PCMSO',
    'eSocial/PPP eletrônico',
    'Exames Ocupacionais',
    'Sistema de Gestão de SST',
    'Ordem de Serviço',
    'Controle de entrega de EPI',
    'Gestão de Treinamentos',
    'Relatórios de Convocação de Periódicos',
    'Agendamento Online',
    'Guarda de Prontuário',
    'Relatório Anual PCMSO'
  ]
};

export const ADDITIONAL_SERVICES = [
  { item: 'Emissão de PPP – período Reque SST responsável', value: 30.00 },
  { item: 'Emissão de PPP – período anterior à Reque SST', value: 250.00 },
  { item: 'Customização de Ordem de Serviço por cargo*', value: 75.00 },
  { item: 'Cadastro manual funcionário no SOC', value: 25.00 },
];

export const SYSTEM_FEATURES = [
  "Agendamento On-line dos exames",
  "Relatório de exames realizados por funcionário",
  "Relação de riscos e exames por cargo",
  "Gestão de EPI",
  "Relatório de funcionários ativos",
  "Geração de registros e mensageria do eSocial",
  "Cadastro de novos funcionários",
  "Gestão de Treinamentos",
  "Emissão de PPP",
  "Relatório de exames realizados",
  "Info. dos exames agendados por e-mail",
  "Controle e emissão de Ordens de Serviço",
  "Gestão de convocação de exames periódicos",
  "Registro e controle estatístico de ocorrências"
];

export const UNIT_EXAM_TABLES: Record<RequeUnit, ExamItem[]> = {
  [RequeUnit.PONTA_GROSSA]: [
    { category: 'Exame Médico', name: 'EXAME CLÍNICO OCUPACIONAL', price: 36.69, deadline: 'a depender dos demais exames' },
    { category: 'Complementares', name: 'ACUIDADE VISUAL', price: 9.57, deadline: 'na hora' },
    { category: 'Complementares', name: 'AUDIOMETRIA', price: 27.42, deadline: 'na hora' },
    { category: 'Complementares', name: 'ELETROCARDIOGRAMA', price: 38.32, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ELETROENCEFALOGRAMA', price: 83.01, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ESPIROMETRIA SEM LAUDO', price: 25.55, deadline: 'na hora' },
    { category: 'Complementares', name: 'ESPIROMETRIA COM LAUDO', price: 35.14, deadline: 'na hora' },
    { category: 'Complementares', name: 'AV. PSICOSSOCIAL', price: 76.28, deadline: 'na hora' },
    { category: 'Complementares', name: 'AV. PSICOTÉCNICA', price: 114.93, deadline: 'na hora' },
    { category: 'Imagem', name: 'RX TORÁX PA - PADRÃO OIT', price: 157.81, deadline: 'mesmo dia' },
    { category: 'Imagem', name: 'RX TORÁX PA', price: 52.46, deadline: 'mesmo dia' },
    { category: 'Imagem', name: 'RX TORÁX PA E PERFIL', price: 52.46, deadline: 'mesmo dia' },
    { category: 'Imagem', name: 'RX DE COLUNA LOMBAR (AP+P)', price: 65.37, deadline: 'mesmo dia' },
    { category: 'Toxicológico', name: 'TOXICOLÓGICO CLT', price: 94.35, deadline: 'negativo 3 dias, positivo 5 dias' },
    { category: 'Toxicológico', name: 'TOXICOLÓGICO CNH', price: 94.35, deadline: 'negativo 3 dias, positivo 5 dias' },
    { category: 'Laboratorial', name: 'AC. HIPÚRICO', price: 16.15, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'AC. MANDELICO', price: 32.32, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'AC. METIL HIPÚRICO', price: 16.15, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'AC.. ÚRICO', price: 8.81, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'BETA HCG', price: 19.62, deadline: 'em 1 dia' },
    { category: 'Laboratorial', name: 'CARBOXIHEMOGLOBINA', price: 36.72, deadline: '4 dias úteis' },
    { category: 'Laboratorial', name: 'CHUMBO', price: 42.59, deadline: '4 dias úteis' },
    { category: 'Laboratorial', name: 'COLESTEROL TOTAL', price: 8.81, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'COLESTEROL HDL', price: 11.98, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'COLINESTERASE', price: 16.72, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'COPROCULTURA', price: 17.40, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'CREATINA', price: 6.61, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GAMA GT', price: 9.55, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GLICEMIA', price: 6.61, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'HEMOGRAMA COMPLETO', price: 14.23, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'MICOLOGICO DIRETO', price: 23.90, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'METIL ETIL CETONA', price: 25.10, deadline: '6 dias úteis' },
    { category: 'Laboratorial', name: 'PARASITOLÓGICO - EPF', price: 16.67, deadline: 'em 1 dia' },
    { category: 'Laboratorial', name: 'PARCIAL DE URINA', price: 10.06, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'PSA TOTAL', price: 46.67, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TGO', price: 9.55, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TGP', price: 9.55, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TIPO SANGUINEO', price: 10.27, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TOXOPLASMOSE IGG', price: 36.72, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TOXOPLASMOSE IGM', price: 36.72, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TSH', price: 36.72, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'VDRL', price: 11.76, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'VHS', price: 8.81, deadline: 'mesmo dia' },
  ],
  [RequeUnit.CASTRO]: [
    { category: 'Exame Médico', name: 'EXAME CLÍNICO OCUPACIONAL', price: 46.13, deadline: 'a depender dos demais exames' },
    { category: 'Complementares', name: 'ACUIDADE VISUAL', price: 18.21, deadline: 'na hora' },
    { category: 'Complementares', name: 'AUDIOMETRIA', price: 31.44, deadline: 'na hora' },
    { category: 'Complementares', name: 'ELETROCARDIOGRAMA', price: 54.63, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ELETROENCEFALOGRAMA', price: 115.32, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ESPIROMETRIA SEM LAUDO', price: 35.20, deadline: 'na hora' },
    { category: 'Complementares', name: 'ESPIROMETRIA COM LAUDO', price: 37.65, deadline: 'na hora' },
    { category: 'Complementares', name: 'AV. PSICOSSOCIAL', price: 54.63, deadline: 'na hora' },
    { category: 'Complementares', name: 'AV. PSICOTÉCNICA', price: 109.84, deadline: 'na hora' },
    { category: 'Imagem', name: 'RX TORÁX PA - PADRÃO OIT', price: 157.81, deadline: '2 dias úteis' },
    { category: 'Imagem', name: 'RX TORÁX PA', price: 97.11, deadline: '2 dias úteis' },
    { category: 'Imagem', name: 'RX DE COLUNA LOMBAR (AP+P)', price: 103.3, deadline: '2 dias úteis' },
    { category: 'Toxicológico', name: 'TOXICOLÓGICO CLT', price: 136.28, deadline: 'negativo 3 dias, positivo 5 dias' },
    { category: 'Toxicológico', name: 'TOXICOLÓGICO CNH', price: 136.28, deadline: 'negativo 3 dias, positivo 5 dias' },
    { category: 'Laboratorial', name: 'AC. HIPÚRICO', price: 17.49, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'AC. MANDELICO', price: 28.90, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'AC. METIL HIPÚRICO', price: 17.49, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'AC.. ÚRICO', price: 6.03, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'BETA HCG', price: 19.62, deadline: 'em 1 dia' },
    { category: 'Laboratorial', name: 'CARBOXIHEMOGLOBINA', price: 20.02, deadline: '4 dias úteis' },
    { category: 'Laboratorial', name: 'CHUMBO', price: 32.12, deadline: '4 dias úteis' },
    { category: 'Laboratorial', name: 'COLESTEROL TOTAL', price: 6.70, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'COLESTEROL HDL', price: 12.40, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'COLINESTERASE', price: 12.12, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'COPROCULTURA', price: 18.08, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'CREATINA', price: 6.35, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GAMA GT', price: 6.71, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GLICEMIA', price: 6.51, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'HEMOGRAMA COMPLETO', price: 14.49, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'MICOLOGICO DIRETO', price: 11.08, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'METIL ETIL CETONA', price: 24.94, deadline: '6 dias úteis' },
    { category: 'Laboratorial', name: 'PARASITOLÓGICO - EPF', price: 20.71, deadline: 'em 1 dia' },
    { category: 'Laboratorial', name: 'PARCIAL DE URINA', price: 9.98, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'PSA TOTAL', price: 48.85, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TGO', price: 5.99, deadline: 'mesmo dia' },
    /* Fix missing 'name' property on line 196 */
    { category: 'Laboratorial', name: 'TGP', price: 5.96, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TIPO SANGUINEO', price: 14.74, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TOXOPLASMOSE IGG', price: 31.67, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TOXOPLASMOSE IGM', price: 31.67, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TSH', price: 24.92, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'VDRL', price: 7.15, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'VHS', price: 7.57, deadline: 'mesmo dia' },
  ],
  [RequeUnit.GUARAPUAVA]: [
    { category: 'Exame Médico', name: 'EXAME CLÍNICO OCUPACIONAL', price: 40.00, deadline: 'a depender dos demais exames' },
    { category: 'Complementares', name: 'ACUIDADE VISUAL', price: 15.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'AUDIOMETRIA OCUPACIONAL', price: 26.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'AUDIOMETRIA TONAL', price: 30.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'AUDIOMETRIA VOCAL', price: 50.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'ELETROCARDIOGRAMA', price: 50.00, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ELETROENCEFALOGRAMA', price: 90.00, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ESPIROMETRIA COM LAUDO', price: 25.00, deadline: 'na hora' },
    { category: 'Imagem', name: 'RX TORÁX PA - PADRÃO OIT', price: 60.00, deadline: 'mesmo dia' },
    { category: 'Imagem', name: 'RX TORÁX PA', price: 60.00, deadline: 'mesmo dia' },
    { category: 'Imagem', name: 'RX TORÁX PA E PERFIL', price: 50.00, deadline: 'mesmo dia' },
    { category: 'Imagem', name: 'RX DE COLUNA LOMBAR (AP+P)', price: 50.00, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'AC. HIPÚRICO', price: 16.71, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'AC. MANDELICO', price: 25.00, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'AC. METIL HIPÚRICO', price: 16.71, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'BETA HCG', price: 18.58, deadline: 'em 1 dia' },
    { category: 'Laboratorial', name: 'CHUMBO', price: 27.00, deadline: '4 dias úteis' },
    { category: 'Laboratorial', name: 'COLESTEROL TOTAL', price: 7.10, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'COLESTEROL HDL', price: 7.10, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'COLINESTERASE', price: 15.00, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'COPROCULTURA', price: 23.00, deadline: '3 dias úteis' },
    { category: 'Laboratorial', name: 'CREATINA', price: 4.66, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GAMA GT', price: 5.41, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GLICEMIA', price: 5.22, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'HEMOGRAMA COMPLETO', price: 9.34, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'METIL ETIL CETONA', price: 22.60, deadline: '6 dias úteis' },
    { category: 'Laboratorial', name: 'PARASITOLÓGICO - EPF', price: 7.28, deadline: 'em 1 dia' },
    { category: 'Laboratorial', name: 'TGO', price: 5.22, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'TGP', price: 5.22, deadline: 'mesmo dia' },
  ],
  [RequeUnit.IPIRANGA]: [
    { category: 'Exame Médico', name: 'EXAME CLÍNICO OCUPACIONAL', price: 55.00, deadline: 'a depender dos demais exames' },
    { category: 'Complementares', name: 'ACUIDADE VISUAL', price: 15.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'AUDIOMETRIA', price: 50.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'ELETROCARDIOGRAMA', price: 45.00, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ELETROENCEFALOGRAMA', price: 75.00, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ESPIROMETRIA COM LAUDO', price: 30.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'AV. PSICOSSOCIAL', price: 65.00, deadline: 'na hora' },
    { category: 'Laboratorial', name: 'CREATINA', price: 15.00, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GAMA GT', price: 15.00, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GLICEMIA', price: 20.00, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'METIL ETIL CETONA', price: 25.00, deadline: '6 dias úteis' },
    { category: 'Laboratorial', name: 'PARASITOLÓGICO - EPF', price: 20.00, deadline: 'em 1 dia' },
  ],
  [RequeUnit.IVAI]: [
    { category: 'Exame Médico', name: 'EXAME CLÍNICO OCUPACIONAL', price: 50.00, deadline: 'a depender dos demais exames' },
    { category: 'Complementares', name: 'ACUIDADE VISUAL', price: 15.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'AUDIOMETRIA', price: 50.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'ELETROCARDIOGRAMA', price: 45.00, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ELETROENCEFALOGRAMA', price: 75.00, deadline: 'mesmo dia' },
    { category: 'Complementares', name: 'ESPIROMETRIA COM LAUDO', price: 30.00, deadline: 'na hora' },
    { category: 'Complementares', name: 'AV. PSICOSSOCIAL', price: 65.00, deadline: 'na hora' },
    { category: 'Laboratorial', name: 'CREATINA', price: 15.00, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GAMA GT', price: 15.00, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'GLICEMIA', price: 25.00, deadline: 'mesmo dia' },
    { category: 'Laboratorial', name: 'METIL ETIL CETONA', price: 25.00, deadline: '6 dias úteis' },
    { category: 'Laboratorial', name: 'PARASITOLÓGICO - EPF', price: 20.00, deadline: 'em 1 dia' },
    { category: 'Laboratorial', name: 'VHS', price: 50.00, deadline: 'mesmo dia' },
  ],
};
